/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Sent by the client in requests to create a new item in the system
 * @export
 * @interface ItemNew
 */
export interface ItemNew {
    /**
     * 
     * @type {string}
     * @memberof ItemNew
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ItemNew
     */
    price: number;
}

export function ItemNewFromJSON(json: any): ItemNew {
    return ItemNewFromJSONTyped(json, false);
}

export function ItemNewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemNew {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'price': json['price'],
    };
}

export function ItemNewToJSON(value?: ItemNew | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'price': value.price,
    };
}


