/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Sent by the client in requests to create a new user in the system
 * @export
 * @interface UserNew
 */
export interface UserNew {
    /**
     * 
     * @type {string}
     * @memberof UserNew
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserNew
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserNew
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserNew
     */
    password: string;
}

export function UserNewFromJSON(json: any): UserNew {
    return UserNewFromJSONTyped(json, false);
}

export function UserNewFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserNew {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'email': json['email'],
        'name': json['name'],
        'password': json['password'],
    };
}

export function UserNewToJSON(value?: UserNew | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'email': value.email,
        'name': value.name,
        'password': value.password,
    };
}


